Add add_texture functionality to graphics lib - Fix #105
NadzwyczajnaGrupaRobocza/bomberman pull request #124
Opened 2019-07-05 05:30 UTC by Abergard

- additionally make white color a default color

2019-07-07 19:47 UTC, kn65op commented
I think better name for images would be resources.

2019-07-07 19:48 UTC, kn65op commented on src/graphics/includes/graphics/renderer_pool.hpp
> +                                const color& = graphics::colors::white) = 0;
Can't we override this method with option to set texture_path instead of color?

2019-08-16 08:19 UTC, kn65op submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 16 files at r1, 29 of 29 files at r2.
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/124#-:-LmOV_LZ3dfsDwtmLYvI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @moose-x86)



<!-- Sent from Reviewable.io -->

2019-08-17 08:44 UTC, kn65op requested changes
> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/124)* status: all files reviewed, 1 unresolved discussion (waiting on @Abergard and @moose-x86)

___
*[src/graphics/src/texture_warehous.hpp, line 12 at r3](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/124#-LmTjtTY3dpYs0XJpUKF:-LmTjtTY3dpYs0XJpUKG:btf4w5c) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/a0394a938d539626a32530a12c439f1e564d4b15/src/graphics/src/texture_warehous.hpp#L12)):*
> ```cpp
> using texture_path = std::string;
> 
> class texture_warehous
> ```

Shouldn't be werehous**e**?


<!-- Sent from Reviewable.io -->

2019-08-17 08:59 UTC, Abergard reviewed
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/124)* status: all files reviewed, 1 unresolved discussion (waiting on @kn65op and @moose-x86)

___
*[src/graphics/src/texture_warehous.hpp, line 12 at r3](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/124#-LmTjtTY3dpYs0XJpUKF:-LmTnHO09qSuSasFreuN:b-w13az3) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/a0394a938d539626a32530a12c439f1e564d4b15/src/graphics/src/texture_warehous.hpp#L12)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

Shouldn't be werehous**e**?
</blockquote></details>

Yes, it should be


<!-- Sent from Reviewable.io -->

2019-08-17 09:00 UTC, Abergard reviewed
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/124)* status: 21 of 31 files reviewed, 1 unresolved discussion (waiting on @kn65op and @moose-x86)

___
*[src/graphics/src/texture_warehous.hpp, line 12 at r3](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/124#-LmTjtTY3dpYs0XJpUKF:-LmTndlj-avOyuhDAd_9:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/a0394a938d539626a32530a12c439f1e564d4b15/src/graphics/src/texture_warehous.hpp#L12)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

Yes, it should be
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-08-17 20:28 UTC, kn65op approved these changes
> Reviewed 10 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/124)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @moose-x86)



<!-- Sent from Reviewable.io -->

2019-08-18 19:44 UTC, merged